goroutine:
  max-goroutine: 2000 #goroutine池最大线程数
  core-goroutine: 1000  #goroutine池核心线程数
  timeout: 5 #goroutine池等待超时时间 单位秒

database:
  type: mongodb
  host: 172.23.52.164
  port: 27017
  user: root
  password: weizixiang

BGP:
  frequency: 1 # BGP数据采集频率 单位小时
  storage-path: D:/code/platform/BGP/data/unprocessed # BGP原始数据存储路径
  processed-path: D:/code/platform/BGP/data/processed # BGP处理后数据存储路径
  storage-time: 10 # BGP原始数据存储 保留时间 单位天
  processed-time: 10 # BGP处理后数据存储 保留时间 单位天